I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/minigame.rpy", line 194, in script
    python:
  File "game/minigame.rpy", line 196, in <module>
    print(datingPool[len(datingPool)-1].name)
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/minigame.rpy", line 194, in script
    python:
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/minigame.rpy", line 196, in <module>
    print(datingPool[len(datingPool)-1].name)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\revertable.py", line 221, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
FishLoveMe 1.0
Sat May  4 22:53:46 2024
